services:
  db:
    image: postgres:15
    container_name: credit-contract-database
    restart: always
    environment:
      POSTGRES_DB: credit_contract_database
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: