# Generated by Django 5.2.2 on 2025-06-09 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active?"),
                ),
                ("country", models.CharField(max_length=150, verbose_name="Country")),
                ("state", models.CharField(max_length=150, verbose_name="State")),
                ("city", models.CharField(max_length=150, verbose_name="City")),
                (
                    "neighborhood",
                    models.CharField(max_length=150, verbose_name="Neighborhood"),
                ),
                ("street", models.CharField(max_length=150, verbose_name="Street")),
                (
                    "number",
                    models.CharField(blank=True, max_length=150, verbose_name="Number"),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Complement"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=150, verbose_name="Postal code"),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "db_table": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active?"),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="External id"
                    ),
                ),
                ("emission_date", models.DateField(verbose_name="Emission date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Rate"
                    ),
                ),
                (
                    "borrower_document",
                    models.CharField(max_length=11, verbose_name="Borrower document"),
                ),
                (
                    "borrower_birthdate",
                    models.DateField(verbose_name="Borrower birthdate"),
                ),
                (
                    "borrower_phone",
                    models.CharField(max_length=15, verbose_name="Borrower phone"),
                ),
                (
                    "borrower_address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contracts.address",
                        verbose_name="Borrower address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract",
                "verbose_name_plural": "Contracts",
                "db_table": "contracts",
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active?"),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Number")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Amount"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Due date")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="contracts.contract",
                        verbose_name="Contract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Installment",
                "verbose_name_plural": "Installments",
                "db_table": "installments",
            },
        ),
    ]
